### PR TITLE
Fix bugs in emigration rate calculation

### PR DESCRIPTION
**Pull request by zmbc**
The bugs:
* The at risk population was not being calculated correctly.
* The indexes were not being matched up correctly when applying the proportions, leading to a substantial underestimate of the rates.

In order to address the second bug I have pulled in more code from VEHSS that does the distributing-by-proportions operation.

**NOTE:** The main notebook has only be re-run with a smaller population. I re-ran with a large population in three separate notebooks.

### CODE REVIEW

**Comment by NathanielBlairStahn** [comment]
Hey @zmbc , I started looking over this, but there's a lot here that I'm not familiar with. If you want feedback on it, I think it would be easiest if we met to go over it together so you could explain what's going on and which parts I should pay most attention to.

**Comment by zmbc** [comment]
@NathanielBlairStahn thanks for taking a look, and sorry for the delay in responding! Let's find a time to discuss.

**Review by aflaxman — APPROVED** [review]
Can you include the visual comparison of the large run before and after this fix in this PR (or on slack if that is easier)?

**Comment by zmbc** [comment]
Before (large population, with bugs) vs after (large population, after this change).

**Non-reference-person emigration:**

Before:

image

After:

image

Interpretation: looks broadly similar, but much higher, which is good.

**GQ person emigration:**

Before:

image

After:

image

Interpretation: Increased a fair amount, though the spikes around age 18 decreased. The other striking feature is the under-18 not born in the US; correcting the at-risk population will have made this denominator very small, leading to a lot more variability. This won't matter much since our population in this category in the sim will also be very small.

**Household emigration:**

Before:

image

After:

image

Interpretation: Increased a lot. Also looks significantly smoother than before; I don't know exactly why this is, but it doesn't seem wrong -- emigration decreasing with age makes sense. Again, there are some visually striking differences in under-18, but these are not super impactful since they are about reference people (who will rarely be that young in our simulation).

**Pull request merged**
